---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://git.f-brinker.de/fbrinker/elderscrolls-addon-achievementInfo.git sources
  - cd sources && git checkout $DRONE_COMMIT

- name: lint
  image: alpine
  commands:
    - apk update
    - apk add --no-cache build-base curl unzip
    - apk add --no-cache lua5.1 lua5.1-dev luarocks5.1
    - luarocks-5.1 install luacheck
    - cd sources
    - luacheck ./*.lua

- name: build
  image: alpine
  commands:
    - apk update && apk add --no-cache zip
    # Delete unneeded files/dirs
    - rm -rf sources/{.git,.drone.yml,.luacheckrc}
    # Set Version and AddonVersion
    - export VERSION=$DRONE_TAG
    - export ADDON_VERSION=$(echo $DRONE_TAG | sed -E 's/(0|)\.//g')
    - sed -i "s/\"%VERSION%\"/$VERSION/g" sources/AchievementInfoCommon.lua
    - sed -i "s/%VERSION%/$VERSION/g" sources/AchievementInfo.txt
    - sed -i "s/%ADDON_VERSION%/$ADDON_VERSION/g" sources/AchievementInfo.txt
    # Rename and zip
    - mv sources AchievementInfo
    - zip -r "AchievementInfo-$DRONE_TAG.zip" ./AchievementInfo
  when:
    event: 
      - tag

- name: release
  image: plugins/gitea-release
  settings:
    base_url: https://git.f-brinker.de
    api_key:
      from_secret: gitea_token
    files: ./*.zip
    title: AchievementInfo ${DRONE_TAG}
    note: AchievementInfo/CHANGELOG.md
  when:
    event: 
      - tag
